import argparse
from util.read_category_table import read_df, read_srr_dir
import pandas as pd
import numpy as np
import os



def gsm_seq(df, srr_dict, path_seq_csv):
    """Receives a file separated by pipe
    containing GSM, SRX, SRR, Category,
    a dict generated by read_srr_dir
    The output file will be passed as argument
    (sample) to chipseq_json_generator (GSM,sequencing) """
    
    gsm_dict = dict()
    output = open(os.path.join(path_seq_csv,"seq_type.csv"), 'w')
    
    for k in srr_dict.keys():
        for i, row in df.iterrows():
            if k in row['SRR']:
                gsm_dict[row['GSM']] = srr_dict[k]
                break 

    for k in gsm_dict.keys():
        string = k + "," + gsm_dict[k] + "\n"
        output.write(string)
    output.close()


def main():
    df = read_df(args.table)
    #print(df)
    srr_dict = read_srr_dir(args.path)
    path_seq_csv = args.path.replace("data_srr", "")
    gsm_seq_type = gsm_seq(df, srr_dict, path_seq_csv)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="")

    parser.add_argument('-t', '--table', action="store",
                        help='The Category table with GSM, SRX, SRR, Category columns',
                        required=True)

    parser.add_argument('-p', '--path', action="store",
                        help='Absolute path to SRR data directory',
                        required=True)




args = parser.parse_args()
main()
