import argparse
from util.read_category_table import read_df, read_srr_dir
import pandas as pd
import numpy as np




def gsm_seq(df, srr_dict):
    
    '''Function to create the file seq_type.csv that contains the sequence type classification per sample.
    You need to give the table (dataframe) and the srr_dict generated by read_srr_dir(srr_path) (dict that
    contains the srr as key and single or paired end as value).
    This output file will be passed as argument (sample) to chipseq_json_generator'''

    gsm_dict = dict()
    output = open("seq_type.csv", 'w')
    
    for k in srr_dict.keys():
        for i, row in df.iterrows():
            if k in row['SRR']:
                gsm_dict[row['GSM']] = srr_dict[k]
                break 

    for k in gsm_dict.keys():
        string = k + "," + gsm_dict[k] + "\n"
        output.write(string)
    output.close()


def main():
    df = read_df(args.table)
    #print(df)
    srr_dict = read_srr_dir(args.path)
    gsm_seq_type = gsm_seq(df, srr_dict)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="")

    parser.add_argument('-t', '--table', action="store",
                        help='The Category table with GSM, SRX, SRR, Category columns',
                        required=True)

    parser.add_argument('-p', '--path', action="store",
                        help='Absolute path to SRR data directory',
                        required=True)




args = parser.parse_args()
main()